import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      <Image
      src="/logo.png"
      width={500}
      height={500}
      alt="Picture of the author"
      />
      <h2> Build using Next JS  , deployed on vercel </h2>      
        
      </main>
    </div>
  );
};

export default Home;
